stages:
  - install
  - deploy

default:
  cache: &cache
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
      - ./node_modules
      - apps/**/node_modules
    policy: pull

before_script:
  - npm i -g pnpm --registry=https://registry.npmmirror.com
  - pnpm setup
  - source /root/.bashrc
  - pnpm config set store-dir .pnpm-store
  - pnpm i -g @cloudbase/cli --registry=https://registry.npmmirror.com

install_admin_js:
  stage: install
  image: node:18
  interruptible: true
  cache:
    <<: *cache
    policy: push
  script:
    - pnpm install --registry=https://registry.npmmirror.com
  tags:
    - ytweb

deploy_admin_test:
  stage: deploy
  image: node:18
  only:
    changes:
      - apps/ad-dashboard-admin/**/*
    refs:
      - /^feat_.*$/
      - develop
  script:
    - echo "构建后台"
    - pnpm -v
    - npm run deploy
  tags:
    - ytweb
  artifacts:
    paths:
      - dist

deploy_admin_prod:
  stage: deploy
  image: node:18
  only:
    changes:
      - apps/ad-dashboard-admin/**/*
    refs:
      - master
  when: manual
  script:
    - echo "构建后台"
    - pnpm -v
    - npm run deploy:prod
  tags:
    - ytweb
  artifacts:
    paths:
      - dist
